# Generated by Django 3.2.10 on 2022-01-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_add_post_model_for_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории, обязательное, 100 символов.', max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория статьи',
                'verbose_name_plural': 'Категория статей',
                'db_table': 'blog_category',
            },
        ),
    ]
