# Generated by Django 3.2.10 on 2022-01-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_create_category_model_for_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.categorymodel', verbose_name='Категория статьи'),
        ),
    ]
