# Generated by Django 3.2.10 on 2022-01-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_foreignkey_for_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Публиковать да/нет ?'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
