# Generated by Django 3.2.10 on 2022-01-29 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_field_for_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст комментария')),
                ('parent_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postmodel', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий для поста',
                'verbose_name_plural': 'Комментарии для постов',
                'db_table': 'blog_commentary',
            },
        ),
    ]
