# Generated by Django 3.2.10 on 2022-01-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_create_model_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_tags',
            field=models.ManyToManyField(blank=True, to='blog.TagsModel'),
        ),
    ]
