# Generated by Django 3.2.10 on 2022-01-30 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_add_link_post_on_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentarymodel',
            options={'ordering': ('create_date',), 'verbose_name': 'Комментарий для поста', 'verbose_name_plural': 'Комментарии для постов'},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('create_date',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='commentarymodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentarymodel',
            name='parent_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentary', to='blog.postmodel', verbose_name='Пост'),
        ),
    ]
